services:
  gateway:
    build: ./gateway
    container_name: yoda-api-gateway
    restart: unless-stopped

  dispatcher:
    build: ./dispatcher
    container_name: yoda-dispatcher
    restart: unless-stopped